productsSample = [
    "Do you have the latest iPhone available?",
    "What is the price of the Samsung Galaxy S21?",
    "Does the OnePlus 9 Pro come in green?",
    "What are the specifications of the Google Pixel 6?",
    "Is the Huawei P50 Pro available in your store?",
    "What colors does the iPhone 13 come in?",
    "Are there any discounts for the Samsung Galaxy Note 20?",
    "Is the Sony Xperia 1 III available?",
    "Does your store have the latest Google Pixel?",
    "Are there any promotions for the OnePlus Nord?",
    "What is the storage capacity of the Samsung Galaxy S21?",
    "Is the iPhone SE 2022 available?",
    "What is the price difference between the iPhone 12 and 13?",
    "Is the Motorola Edge 20 available?",
    "Is the Google Pixel 6 Pro available in your store?",
    "Do you sell the Xiaomi Mi 11?",
    "Are there any offers for the Samsung Galaxy Z Fold 3?",
    "Is the Oppo Find X3 Pro available?",
    "What are the features of the iPhone 13 Pro?",
    "Is the LG Wing available?",
    "Is the Nokia 8.3 5G available?",
    "Is the Asus ROG Phone 5 available?",
    "Do you have the Realme GT?",
    "Is the Vivo X60 Pro available?",
    "Do you have the Honor 50?",
    "What is the battery life of the Samsung Galaxy A52?",
    "Is the ZTE Axon 30 available?",
    "Do you have the BlackBerry KEY2?",
    "What is the screen size of the iPhone 13 Mini?",
    "Do you have the TCL 20 Pro 5G?",
    "Is the Nokia XR20 available in your store?",
    "What is the price of the Samsung Galaxy S20 FE?",
    "Do you have the iPhone 12 Pro Max?",
    "Is the Redmi Note 10 Pro available?",
    "What is the difference between the iPhone 12 and iPhone 13?",
    "Do you have the Sony Xperia 5 II?",
    "What is the warranty period of the Samsung Galaxy S21?",
    "Is the Google Pixel 5a available?",
    "Do you have the OnePlus 8T?",
    "What is the price of the iPhone 13 Pro Max?",
    "Is the Samsung Galaxy Z Flip 3 available?",
    "What are the specifications of the Oppo Reno6 Pro?",
    "Do you have the Vivo V21?",
    "Is the Motorola Moto G100 available?",
    "Do you have the Huawei Mate 40 Pro?",
    "Is the Realme 8 Pro available in your store?",
    "Is the Asus Zenfone 8 available?",
    "Is the LG Velvet available?",
    "What is the storage capacity of the iPhone 12?",
    "Do you have the Honor Magic 3?",
    "Is the Xiaomi Mi 11 Ultra available?"
]

chitchatSample = [
    "What is the weather like today?",
    "How hot is it outside?",
    "Will it rain tomorrow?",
    "What is the current temperature?",
    "Can you tell me the current weather conditions?",
    "Will it be sunny this weekend?",
    "What was the temperature yesterday?",
    "How cold will it get tonight?",
    "Who was the first president of the United States?",
    "In what year did World War II end?",
    "Can you tell me about the history of the internet?",
    "In what year was the Eiffel Tower built?",
    "Who invented the telephone?",
    "What is your name?",
    "Do you have a name?",
    "What should I call you?",
    "Who created you?",
    "How old are you?",
    "Can you tell me an interesting fact?",
    "Do you know any interesting riddles?",
    "What is your favorite color?",
    "What is your favorite movie?",
    "Do you have any hobbies?",
    "What is the meaning of life?",
    "Can you tell me a joke?",
    "What is the capital of France?",
    "What is the world's population?",
    "How many continents are there?",
    "Who wrote 'To Kill a Mockingbird'?",
    "Can you give me a quote from Albert Einstein?"
]
